# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keyCode', models.CharField(max_length=40)),
                ('tagLine', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='articleImages')),
                ('lid', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=400)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='maininfo',
            name='bgImage',
            field=models.ImageField(null=True, upload_to='siteImages'),
        ),
    ]
