# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170105_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItem', models.CharField(max_length=50)),
                ('menuItemDescription', models.CharField(max_length=50)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
