# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menuitem_menuitemmouseover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='articleImages'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menuItemMouseOver',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
