# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170105_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='bgImage',
            field=models.ImageField(null=True, upload_to='main/static/main/siteImages'),
        ),
    ]
