# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170106_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='bgImage',
            field=models.ImageField(null=True, upload_to='static/main/siteImages'),
        ),
    ]
