# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170106_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=800),
        ),
    ]
