# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170106_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='lid',
        ),
        migrations.AddField(
            model_name='article',
            name='lid1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='lid2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
