# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_menuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='loggedOnly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='loggedOnly',
            field=models.IntegerField(default=0),
        ),
    ]
