# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170108_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=models.TextField(),
        ),
    ]
