# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-08 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170108_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keyCode', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='articleImages')),
                ('dia_l1', models.CharField(blank=True, max_length=100)),
                ('dia_l2', models.CharField(blank=True, max_length=100)),
                ('tagLine', models.CharField(max_length=200)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('active', models.IntegerField(default=1)),
                ('loggedOnly', models.IntegerField(default=0)),
            ],
        ),
    ]
