# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content3',
            field=models.TextField(blank=True),
        ),
    ]
