# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20170108_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
