# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-12 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170108_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
