# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-12 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_article_title3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
