# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_article_itemwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=models.TextField(),
        ),
    ]
