# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-15 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20170115_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='itemWidth',
            field=models.IntegerField(default=3, verbose_name='itemWidth - (12, 6, 3)'),
        ),
    ]
