# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='linkTo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Default: menuItem'),
        ),
    ]
