# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_menuitem_linkto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='surName',
            new_name='cell',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='address2',
            new_name='f2address',
        ),
        migrations.AddField(
            model_name='registration',
            name='f2cell',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2city',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2country',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2email',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2fname',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2nif',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2phone',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='f2zip',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='lame',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='nif',
            field=models.CharField(default=' ', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='linkTo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='linkTo - Default: menuItem'),
        ),
    ]
