# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-03 00:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20170202_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='regDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
