# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20170206_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
